

apiVersion: v1
kind: Secret
metadata:
  name: {{ index .Values.secret.name }}
  namespace: {{ index .Values.namespace }}
type: {{ index .Values.secret.type }}
data:
  CONSUL_HTTP_TOKEN: {{ index .Values.secret.consul.secret | b64enc | quote }}
  VAULT_TOKEN: {{ index .Values.secret.vault.secret | b64enc | quote }}
